# Generated by Django 5.1.7 on 2025-03-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstaking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='userstakingreward',
            name='user_staking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.userstaking'),
        ),
    ]
