# Generated by Django 5.1.7 on 2025-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0003_alter_stakingstage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakinglevel',
            name='max_deposite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='min_deposite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userstakingreward',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
