# Generated by Django 5.1.7 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0004_alter_stakinglevel_max_deposite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakinglevel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
