# Generated by Django 5.1.7 on 2025-03-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0005_alter_stakinglevel_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstaking',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed_prematurely', 'Closed Prematurely')], default='in_progress', max_length=20),
        ),
    ]
