# Generated by Django 5.1.7 on 2025-03-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0006_userstaking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstakingreward',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
