# Generated by Django 5.1.7 on 2025-03-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0007_userstakingreward_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakingstage',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3')], unique=True),
        ),
    ]
