# Generated by Django 5.1.7 on 2025-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0008_alter_stakingstage_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingstage',
            name='days_for_change',
            field=models.IntegerField(default=60),
        ),
    ]
