# Generated by Django 5.1.7 on 2025-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0010_competitions_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=18)),
                ('img', models.ImageField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='competitions',
            name='title',
            field=models.CharField(choices=[('bonus', 'Bonus For Referrals'), ('party', 'Dubai Party')], max_length=24),
        ),
    ]
