# Generated by Django 5.1.7 on 2025-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0012_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('badge_content', models.CharField(max_length=12)),
                ('img', models.ImageField(upload_to='')),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Competitions',
        ),
    ]
