# Generated by Django 5.1.7 on 2025-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0013_competition_delete_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='badge_content',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
