# Generated by Django 5.1.7 on 2025-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0014_alter_competition_badge_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstaking',
            name='withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
