# Generated by Django 5.1.7 on 2025-04-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0015_userstaking_withdrawn_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Wallets',
        ),
    ]
