# Generated by Django 5.1.7 on 2025-04-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0016_delete_banner_delete_commission_delete_competition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakinglevel',
            options={'verbose_name': 'Уровень стейкинга', 'verbose_name_plural': 'Уровни стейкинга'},
        ),
        migrations.AlterModelOptions(
            name='stakingstage',
            options={'verbose_name': 'Этап стейкинга', 'verbose_name_plural': 'Этапы стейкинга'},
        ),
        migrations.AlterModelOptions(
            name='userstaking',
            options={'verbose_name': 'Стейкинг пользователя', 'verbose_name_plural': 'Стейкинги пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userstakingreward',
            options={'verbose_name': 'Награда за стейкинг', 'verbose_name_plural': 'Награды за стейкинг'},
        ),
        migrations.AddField(
            model_name='userstaking',
            name='task_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='level',
            field=models.IntegerField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='max_deposite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальный депозит'),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='min_deposite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный депозит'),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='stakinglevel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.stakingstage', verbose_name='Этап стейкинга'),
        ),
        migrations.AlterField(
            model_name='stakingstage',
            name='days_for_change',
            field=models.IntegerField(default=60, verbose_name='Дней для смены уровня'),
        ),
        migrations.AlterField(
            model_name='stakingstage',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Этап 1'), (2, 'Этап 2'), (3, 'Этап 3')], unique=True, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='stakingstage',
            name='staking_time',
            field=models.IntegerField(verbose_name='Длительность (дни)'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='staking_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.stakinglevel', verbose_name='Уровень стейкинга'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('closed_prematurely', 'Закрыто досрочно')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userstaking',
            name='withdrawn_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выведенная сумма'),
        ),
        migrations.AlterField(
            model_name='userstakingreward',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма (в TON)'),
        ),
        migrations.AlterField(
            model_name='userstakingreward',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='userstakingreward',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Токены'),
        ),
        migrations.AlterField(
            model_name='userstakingreward',
            name='user_staking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staking.userstaking', verbose_name='Стейкинг пользователя'),
        ),
    ]
