# Generated by Django 5.1.7 on 2025-03-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='tasks/icons')),
                ('link', models.URLField()),
                ('reward_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFarmingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farming_task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.farmingtask')),
            ],
        ),
    ]
