# Generated by Django 5.1.7 on 2025-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingtask',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
