# Generated by Django 5.1.7 on 2025-04-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_farmingtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingtask',
            name='en_title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
