# Generated by Django 5.1.7 on 2025-04-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28, verbose_name='Название блока')),
                ('content', models.TextField(verbose_name='Содержимое блока')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость входа (TON)')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Призовой фонд'),
        ),
    ]
