# Generated by Django 5.1.7 on 2025-04-11 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contestinfo_contest_prize_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestinfo',
            options={'verbose_name': 'Блок в конкурсе', 'verbose_name_plural': 'Блоки в конкурсах'},
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contest'),
            preserve_default=False,
        ),
    ]
