# Generated by Django 5.1.7 on 2025-04-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contestinfo_options_contestinfo_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('referral_bonuses', 'Бонусы за рефералов'), ('dubai_party', 'Вечеринка в дубае')], max_length=20, verbose_name='Условие конкурса')),
            ],
            options={
                'verbose_name': 'Условие конкурса',
                'verbose_name_plural': 'Условия конкурса',
            },
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest', verbose_name='Конкурс'),
        ),
    ]
