# Generated by Django 5.1.7 on 2025-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contestcondition_alter_contestinfo_contest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestCondition',
        ),
        migrations.AlterModelOptions(
            name='contestinfo',
            options={'verbose_name': 'Условие конкурса', 'verbose_name_plural': 'Условия конкурса'},
        ),
        migrations.AddField(
            model_name='contest',
            name='condition',
            field=models.CharField(choices=[('referral_bonuses', 'Бонусы за рефералов'), ('dubai_party', 'Вечеринка в дубае')], default=1, max_length=20, verbose_name='Условие конкурса'),
            preserve_default=False,
        ),
    ]
