# Generated by Django 5.1.7 on 2025-04-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usercontest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontest',
            options={'verbose_name': 'Участник конкурса', 'verbose_name_plural': 'Участники конкурса'},
        ),
    ]
