# Generated by Django 5.1.7 on 2025-04-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_usercontest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='en_badge_content',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Англ. Бейдж'),
        ),
        migrations.AddField(
            model_name='contest',
            name='en_title',
            field=models.CharField(default=1, max_length=28, verbose_name='Англ. Название конкурса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='en_content',
            field=models.TextField(default=1, verbose_name='Англ. Содержимое блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestinfo',
            name='en_title',
            field=models.CharField(default=1, max_length=28, verbose_name='Англ. Название блока'),
            preserve_default=False,
        ),
    ]
