# Generated by Django 5.1.7 on 2025-04-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contest_en_badge_content_contest_en_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='en_description',
            field=models.CharField(default=1, max_length=18, verbose_name='Англ. Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='en_title',
            field=models.CharField(default=1, max_length=18, verbose_name='Англ. Заголовок'),
            preserve_default=False,
        ),
    ]
