# Generated by Django 5.1.7 on 2025-03-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], default='deposit', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled'), ('waiting', 'Waiting')], default='waiting', max_length=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
