# Generated by Django 5.1.7 on 2025-04-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.CharField(default=1, max_length=48),
            preserve_default=False,
        ),
    ]
