# Generated by Django 5.1.7 on 2025-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
