# Generated by Django 5.1.7 on 2025-04-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
